apiVersion: apps/v1
kind: Deployment

metadata:
  name: siluku
  namespace: application1
spec:
  replicas: 3

  selector:
    matchLabels:
      app: siluku

  template:
    metadata:
      labels:
        app: siluku

    spec:
      containers:
      - name: siluku

        image: imsprasanth/learning:v1

        ports:
        - containerPort: 80
---
# apiVersion: v1
# kind: Pod

# metadata:
#   name: siluku
#   namespace: application1

# spec:
#   containers:
#     - name: siluku
#       image: imsprasanth/learning:v1
#       ports:
#         - containerPort: 3000