apiVersion: v1
kind: Service

metadata:
  name: siluku-service
  namespace: application1
spec:
  type: NodePort

  selector:
    app: siluku

  ports:
  - port: 80
    targetPort: 80
    nodePort: 30081