pipeline {

    agent any

    environment {

        IMAGE = "imsprasanth/learning:${BUILD_NUMBER}"

    }

    stages {

        stage('Clone Repository') {

            steps {

                git branch: 'main',
                    url: 'https://github.com/pixelcodemaestro/learning_n.git'

            }
        }

        stage('Docker Login') {

            steps {

                sh '''
                echo YOUR_DOCKER_TOKEN | docker login \
                -u imsprasanth \
                --password-stdin
                '''
            }
        }

        stage('Build Docker Image') {

            steps {

                sh '''

                docker build \
                -t $IMAGE .

                '''
            }
        }

        stage('Push Image') {

            steps {

                sh '''

                docker push $IMAGE

                '''
            }
        }

        stage('Update Kubernetes Manifest') {

            steps {

                sh '''

                sed -i "s|imsprasanth/learning:.*|$IMAGE|g" \
                k8s/deployment.yaml

                '''

            }

        }

        stage('Deploy to Kubernetes') {

            steps {

                sh '''

                kubectl apply -f k8s/deployment.yaml

                kubectl apply -f k8s/service.yaml

                '''

            }

        }

        stage('Verify Deployment') {

            steps {

                sh '''

                kubectl rollout status deployment/learning -n test

                kubectl get pods -n test

                kubectl get svc -n test

                '''

            }

        }

    }

}