apiVersion: datadoghq.com/v2alpha1
kind: DatadogAgent
metadata:
  name: datadog
spec:
  global:
    clusterName: learn
    site: datadoghq.com
    credentials:
      apiSecret:
        secretName: datadog-secret
        keyName: api-key
  features:
    liveContainerCollection:
      enabled: true
    orchestratorExplorer:
      enabled: true
    logCollection:
      enabled: true
      containerCollectAll: true