apiVersion: apps/v1
kind: Deployment

metadata:
  name: kkl
  namespace: cartoon
spec:
  replicas: 2

  selector:
    matchLabels:
      app: kkl

  template:
    metadata:
      labels:
        app: kkl

    spec:
      containers:
      - name: kklafeRestart

        image: imsprasanth/kkl:1

        ports:
        - containerPort: 3000