apiVersion: apps/v1
kind: Deployment

metadata:
  name: attendance
  namespace: attendance
spec:
  replicas: 2

  selector:
    matchLabels:
      app: attendance

  template:
    metadata:
      labels:
        app: attendance

    spec:
      containers:
      - name: attendance

        image: imsprasanth/attendance:v2

        ports:
        - containerPort: 3000