apiVersion: apps/v1
kind: Deployment

metadata:
  name: ajith
  namespace: rowdy
spec:
  replicas: 3

  selector:
    matchLabels:
      app: ajith

  template:
    metadata:
      labels:
        app: ajith

    spec:
      containers:
      - name: ajith

        image: imsprasanth/kkl:1

        ports:
        - containerPort: 3000
      resources:
  envFrom:

  - configMapRef:
      name: app-config

      
      username: $APP_NAME
      password: $DB_HOST

        # requests:
        #   cpu: "100m"
        #   memory: "128Mi"

        # limits:
        #   cpu: "500m"
        #   memory: "256Mi"

##kubectl autoscale deployment iphone --cpu-percent=50 --min=1 --max=5  -n marathi
## hey -n 100000 -c 500 http://192.168.49.2:30087