version: '3.9'
services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_USER: analyst
      POSTGRES_PASSWORD: analyst123
      POSTGRES_DB: salesdb
    ports: ["5432:5432"]
    volumes:
      - ./postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
