apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding

metadata:
  name: admin-binding

  namespace: rowdy

subjects:

- kind: ServiceAccount
  name: nadhiya
  namespace: rowdy

- kind: ServiceAccount
  name: partha
  namespace: rowdy

roleRef:

  apiGroup: rbac.authorization.k8s.io

  kind: Role

  name: admin-role