apiVersion: rbac.authorization.k8s.io/v1
kind: Role

metadata:
  name: admin-role
  namespace: application1

rules:
- apiGroups: ["", "apps"]

  resources:
  - pods
  - services
  - deployments
  - replicasets
  - configmaps
  - secrets

  verbs:
  - "*"