apiVersion: batch/v1
kind: Job

metadata:
  name: demo-job
  namespace: application1

spec:
  template:
    spec:
      restartPolicy: Never

      containers:
      - name: demo

        image: busybox

        command:
        - sh
        - -c
        - |
          echo "Job Started"
          sleep 30
          echo "Job Completed"

  backoffLimit: 2