apiVersion: apps/v1
kind: Deployment

metadata:
  name: APP_NAME
  namespace: test

spec:
  replicas: 1

  selector:
    matchLabels:
      app: APP_NAME

  template:
    metadata:
      labels:
        app: APP_NAME

    spec:
      containers:
        - name: APP_NAME
          image: IMAGE_PLACEHOLDER
          imagePullPolicy: Always

          ports:
            - containerPort: 80