name: Build and Deploy to AKS

on:
  push:
    branches:
      - deployment

env:
  APP_NAME: siluku
  IMAGE_NAME: siluku
  NAMESPACE: test
  PROJECT_DIR: Demo-project

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - run: az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build Docker Image
        run: |
          docker build \
            -t ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }} \
            -f "${{ env.PROJECT_DIR }}/Dockerfile" \
            "${{ env.PROJECT_DIR }}"

      - name: Push Docker Image
        run: |
          docker push \
            ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}

      - name: Replace Variables
        run: |
          IMAGE=${{ secrets.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}

          sed -i "s|IMAGE_PLACEHOLDER|$IMAGE|g" "${{ env.PROJECT_DIR }}/k8s/deployment.yaml"

          sed -i "s|APP_NAME|${{ env.APP_NAME }}|g" "${{ env.PROJECT_DIR }}/k8s/deployment.yaml"

          sed -i "s|APP_NAME|${{ env.APP_NAME }}|g" "${{ env.PROJECT_DIR }}/k8s/service.yaml"

      - name: Deploy
        run: |
          kubectl apply -f "${{ env.PROJECT_DIR }}/k8s/"

      - name: Verify Rollout
        run: |
          kubectl rollout status deployment/${{ env.APP_NAME }} \
            -n ${{ env.NAMESPACE }}

      - name: Verify Pods
        run: |
          kubectl get pods -n test

      - name: Verify Services
        run: |
          kubectl get svc -n test


