name: Build and Deploy to AKS

on:
  push:
    branches:
      - deployment

env:
  APP_NAME: siluku
  IMAGE_NAME: siluku

jobs:
  build-and-deploy:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - run: az acr login --name ${{ secrets.ACR_NAME }}

      - name: Build Image
        run: |
          docker build \
          -t ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }} .

      - name: Push Image
        run: |
          docker push \
          ${{ secrets.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}

      - uses: azure/aks-set-context@v4
        with:
          resource-group: ${{ secrets.RESOURCE_GROUP }}
          cluster-name: ${{ secrets.AKS_CLUSTER_NAME }}

      - name: Replace Variables
        run: |
          IMAGE=${{ secrets.ACR_NAME }}.azurecr.io/${{ env.IMAGE_NAME }}:${{ github.sha }}

          sed -i "s|IMAGE_PLACEHOLDER|$IMAGE|g" k8s/deployment.yaml
          sed -i "s|APP_NAME|${{ env.APP_NAME }}|g" k8s/deployment.yaml
          sed -i "s|APP_NAME|${{ env.APP_NAME }}|g" k8s/service.yaml

      - name: Deploy to AKS
        run: |
          kubectl apply -f k8s/

      - name: Verify Deployment
        run: |
          kubectl rollout status deployment/${{ env.APP_NAME }} -n test

      - name: Verify Pods
        run: |
          kubectl get pods -n test

      - name: Verify Services
        run: |
          kubectl get svc -n test


